// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.firebears.subsystems;

import org.firebears.RobotMap;
import org.firebears.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Hopper extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon floorLift = RobotMap.floorfloorLift;
    private final Servo dumperServo = RobotMap.dumperdumperServo;
    
    private boolean floorGoingUp = false;
    private boolean floorGoingDown = false;

    final double MAX_SERVO_VALUE = 0.67;
	final double MIN_SERVO_VALUE = 0.0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void goUp(){
    	floorLift.set(1);
    	floorGoingUp = true;
    }
    
    public void goDown(){
    	floorLift.set(-1);
        floorGoingDown = true;
    }
    
    public double getFloorDirection(){
    	return floorLift.get();
    }
    
	public boolean isFloorHigh() {
		return false;
	}

	public boolean isFloorLow() {
		return false;
	}

	public boolean isRunning() {
		return false;
	}

	public boolean isGoingDown() {
		return floorGoingDown;
	}

	public boolean isGoingUp() {
		return floorGoingUp;
	}
	
	public void raiseDumperServo(){
		dumperServo.set(MAX_SERVO_VALUE);
	}
	public void lowerDumperServo(){
		dumperServo.set(MIN_SERVO_VALUE);
	}
}

